"""add idempotency keys table

Revision ID: 64c227b3776d
Revises: 66e3823ab1fc
Create Date: 2025-12-16 22:29:42.598746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c227b3776d'
down_revision: Union[str, Sequence[str], None] = '66e3823ab1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IdempotencyKeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'user_id', name='uq_key_user')
    )
    op.create_index(op.f('ix_IdempotencyKeys_key'), 'IdempotencyKeys', ['key'], unique=False)
    op.create_index(op.f('ix_IdempotencyKeys_session_id'), 'IdempotencyKeys', ['session_id'], unique=False)
    op.create_index(op.f('ix_IdempotencyKeys_user_id'), 'IdempotencyKeys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_IdempotencyKeys_user_id'), table_name='IdempotencyKeys')
    op.drop_index(op.f('ix_IdempotencyKeys_session_id'), table_name='IdempotencyKeys')
    op.drop_index(op.f('ix_IdempotencyKeys_key'), table_name='IdempotencyKeys')
    op.drop_table('IdempotencyKeys')
    # ### end Alembic commands ###
