"""Descriptive message about your changes

Revision ID: 66e3823ab1fc
Revises: c990d55061da
Create Date: 2025-12-16 18:02:52.887245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66e3823ab1fc'
down_revision: Union[str, Sequence[str], None] = 'c990d55061da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Sessions', 'status',
               existing_type=postgresql.ENUM('UPLOADED', 'QUEUED', 'PROCESSING', 'FAILED', 'DONE', name='job_status'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Sessions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('UPLOADED', 'QUEUED', 'PROCESSING', 'FAILED', 'DONE', name='job_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
