"""add composite_score to sessions

Revision ID: 6bca0908464c
Revises: fd4485ea5e78
Create Date: 2026-09-05 20:57:28.179189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bca0908464c'
down_revision: Union[str, Sequence[str], None] = 'fd4485ea5e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sessions', sa.Column('composite_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sessions', 'composite_score')
    # ### end Alembic commands ###
