"""add raw_deleted_at to sessions

Revision ID: 9b70e9221369
Revises: 9b7169591791
Create Date: 2026-09-05 22:48:13.324066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b70e9221369'
down_revision: Union[str, Sequence[str], None] = '9b7169591791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sessions', sa.Column('raw_deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sessions', 'raw_deleted_at')
    # ### end Alembic commands ###
