"""add slug to sessions

Revision ID: 9b7169591791
Revises: 6bca0908464c
Create Date: 2026-09-05 21:42:38.396220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7169591791'
down_revision: Union[str, Sequence[str], None] = '6bca0908464c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sessions', sa.Column('slug', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_Sessions_slug'), 'Sessions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sessions_slug'), table_name='Sessions')
    op.drop_column('Sessions', 'slug')
    # ### end Alembic commands ###
