"""ReCreate Sessions table

Revision ID: c990d55061da
Revises: 9735bf1941f8
Create Date: 2025-12-15 21:44:06.334595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c990d55061da'
down_revision: Union[str, Sequence[str], None] = '9735bf1941f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'FAILED', 'DONE', name='job_status'), nullable=False),
    sa.Column('raw_blob_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sessions_status'), 'Sessions', ['status'], unique=False)
    op.create_index(op.f('ix_Sessions_user_id'), 'Sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sessions_user_id'), table_name='Sessions')
    op.drop_index(op.f('ix_Sessions_status'), table_name='Sessions')
    op.drop_table('Sessions')
    # ### end Alembic commands ###
