"""add error code and message to sessions

Revision ID: d14464906088
Revises: 64c227b3776d
Create Date: 2025-12-17 00:45:21.608238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14464906088'
down_revision: Union[str, Sequence[str], None] = '64c227b3776d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sessions', sa.Column('render_blob_path', sa.Text(), nullable=True))
    op.add_column('Sessions', sa.Column('error_code', sa.String(length=50), nullable=True))
    op.add_column('Sessions', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sessions', 'error_message')
    op.drop_column('Sessions', 'error_code')
    op.drop_column('Sessions', 'render_blob_path')
    # ### end Alembic commands ###
